### ISSUE TITLE
The batch version is not found?

### ISSUE THREAD

**Issue by thieu1995** [brunolnetto/baryopt#5]
Hi Brunol,
I read on your wiki, you said that the python version has both recursive and batch version of barycenter optimization. But I found the Recursive version only, can you please add the batch version of this algorithm. I may add your algorithm to my "mealpy" library.
https://github.com/brunolnetto/baryopt/blob/master/versions/python/drecexpbary.py

**Comment by brunolnetto** [comment]
Python versions are a a working in progress still. But I thank you for your comments.

**Comment by brunolnetto** [comment]
Sorry for the delay. Here is the batch version: https://github.com/asmovi/baryopt/blob/master/versions/python/baryopt/dbatchbary.py . The example is on [rbaryopt_example.ipynb](https://github.com/brunolnetto/baryopt/blob/master/versions/python/examples/rbaryopt_example.ipynb)
