### ISSUE TITLE
Python version is completely wrong.

### ISSUE THREAD

**Issue by thieu1995** [brunolnetto/baryopt#6]
Hi,

I'm not sure you good at python or not. But your Recursive version on python is completely wrong. 
Variable m_1=0 used in algorithm is not updating, lead to m = e_i and then xhat=z=normal(zeta * deltax_1, sigma).T
So your best solution is always a random vector geneted by normal distribution. 
Please check that again.

**Comment by brunolnetto** [comment]
I thank you for your advices. I mentioned on previous issue that python versions are Work in Progress. I will try to submit its versions today still
